
!```````````````````````````````````````````````````````````````````````````````````````````
! Copyright (c) 09/08/2018 Shahram Yalameha <yalameha93@gmail.com> , <sh.yalameha@sci.ui.ac.ir>, `
!               Please report bugs or suggestions to:  yalameha93@gmail.com                `
!                                                                                          `
!```````````````````````````````````````````````````````````````````````````````````````````
! SUBROUTINE: For 3D matereials; start format of agr file. v.1

SUBROUTINE start_agr(color) 
      IMPLICIT  NONE
  ChARACTER(7),DIMENSION(5) :: color
WRITE(2,'(a)') ' # Grace project file-YLM'
WRITE(2,'(a)') '#'
WRITE(2,'(a)') '@version 50125'
WRITE(2,'(a)') '@page size 792, 612'
WRITE(2,'(a)') '@page scroll 5%'
WRITE(2,'(a)') '@page inout 5%'
WRITE(2,'(a)') '@link page off'
WRITE(2,'(a)') '@map font 8 to "Courier", "Courier"'
WRITE(2,'(a)') '@map font 10 to "Courier-Bold", "Courier-Bold"'
WRITE(2,'(a)') '@map font 11 to "Courier-BoldOblique", "Courier-BoldOblique"'
WRITE(2,'(a)') '@map font 9 to "Courier-Oblique", "Courier-Oblique"'
WRITE(2,'(a)') '@map font 4 to "Helvetica", "Helvetica"'
WRITE(2,'(a)') '@map font 6 to "Helvetica-Bold", "Helvetica-Bold"'
WRITE(2,'(a)') '@map font 7 to "Helvetica-BoldOblique", "Helvetica-BoldOblique"'
WRITE(2,'(a)') '@map font 5 to "Helvetica-Oblique", "Helvetica-Oblique"'
WRITE(2,'(a)') '@map font 14 to "NimbusMonoL-BoldOblique", "NimbusMonoL-BoldOblique"'
WRITE(2,'(a)') '@map font 15 to "NimbusMonoL-Regular", "NimbusMonoL-Regular"'
WRITE(2,'(a)') '@map font 16 to "NimbusMonoL-RegularOblique", "NimbusMonoL-RegularOblique"'
WRITE(2,'(a)') '@map font 17 to "NimbusRomanNo9L-Medium", "NimbusRomanNo9L-Medium"'
WRITE(2,'(a)') '@map font 18 to "NimbusRomanNo9L-MediumItalic", "NimbusRomanNo9L-MediumItalic"'
WRITE(2,'(a)') '@map font 19 to "NimbusRomanNo9L-Regular", "NimbusRomanNo9L-Regular"'
WRITE(2,'(a)') '@map font 20 to "NimbusRomanNo9L-RegularItalic","NimbusRomanNo9L-RegularItalic"'
WRITE(2,'(a)') '@map font 21 to "NimbusSansL-Bold", "NimbusSansL-Bold"'
WRITE(2,'(a)') '@map font 22 to "NimbusSansL-BoldCondensed", "NimbusSansL-BoldCondensed"'
WRITE(2,'(a)') '@map font 23 to "NimbusSansL-BoldCondensedItalic","NimbusSansL-BoldCondensedItalic"'
WRITE(2,'(a)') '@map font 24 to "NimbusSansL-BoldItalic", "NimbusSansL-BoldItalic"'
WRITE(2,'(a)') '@map font 25 to "NimbusSansL-Regular", "NimbusSansL-Regular"'
WRITE(2,'(a)') '@map font 26 to "NimbusSansL-RegularCondensed", "NimbusSansL-RegularCondensed"'
WRITE(2,'(a)') '@map font 27 to "NimbusSansL-RegularCondensedItalic","NimbusSansL-RegularCondensedItalic"'
WRITE(2,'(a)') '@map font 28 to "NimbusSansL-RegularItalic", "NimbusSansL-RegularItalic"'
WRITE(2,'(a)') '@map font 29 to "StandardSymbolsL-Regular", "StandardSymbolsL-Regular"'
WRITE(2,'(a)') '@map font 12 to "Symbol", "Symbol"'
WRITE(2,'(a)') '@map font 2 to "Times-Bold", "Times-Bold"'
WRITE(2,'(a)') '@map font 3 to "Times-BoldItalic", "Times-BoldItalic"'
WRITE(2,'(a)') '@map font 1 to "Times-Italic", "Times-Italic"'
WRITE(2,'(a)') '@map font 0 to "Times-Roman", "Times-Roman"'
WRITE(2,'(a)') '@map font 35 to "URWBookmanL-DemiBold", "URWBookmanL-DemiBold"'
WRITE(2,'(a)') '@map font 36 to "URWBookmanL-DemiBoldItalic", "URWBookmanL-DemiBoldItalic"'
WRITE(2,'(a)') '@map font 37 to "URWBookmanL-Light", "URWBookmanL-Light"'
WRITE(2,'(a)') '@map font 38 to "URWBookmanL-LightItalic", "URWBookmanL-LightItalic"'
WRITE(2,'(a)') '@map font 39 to "URWChanceryL-MediumItalic", "URWChanceryL-MediumItalic"'
WRITE(2,'(a)') '@map font 40 to "URWGothicL-Book", "URWGothicL-Book"'
WRITE(2,'(a)') '@map font 41 to "URWGothicL-BookOblique", "URWGothicL-BookOblique"'
WRITE(2,'(a)') '@map font 42 to "URWGothicL-Demi", "URWGothicL-Demi"'
WRITE(2,'(a)') '@map font 43 to "URWGothicL-DemiOblique", "URWGothicL-DemiOblique"'
WRITE(2,'(a)') '@map font 44 to "URWPalladioL-Bold", "URWPalladioL-Bold"'
WRITE(2,'(a)') '@map font 45 to "URWPalladioL-BoldItalic", "URWPalladioL-BoldItalic"'
WRITE(2,'(a)') '@map font 46 to "URWPalladioL-Italic", "URWPalladioL-Italic"'
WRITE(2,'(a)') '@map font 47 to "URWPalladioL-Roman", "URWPalladioL-Roman"'
WRITE(2,'(a)') '@map font 13 to "ZapfDingbats", "ZapfDingbats"'
WRITE(2,'(a)') '@map color 0 to (255, 255, 255), "white"'
WRITE(2,'(3a)') '@map color 1 to (0, 0, 0), "',color(1),'"' !black
WRITE(2,'(3a)') '@map color 2 to (255, 0, 0), "',color(2),'"' !red
WRITE(2,'(3a)') '@map color 3 to (0, 255, 0), "',color(3),'"' !green
WRITE(2,'(3a)') '@map color 4 to (0, 0, 255), "',color(4),'"'  !blue
WRITE(2,'(a)') '@map color 5 to (148, 0, 211), "violet"'
WRITE(2,'(a)') '@map color 6 to (255, 165, 0), "orange"'
WRITE(2,'(a)') '@map color 7 to (0, 255, 255), "cyan"'
WRITE(2,'(a)') '@map color 8 to (255, 0, 255), "magenta"'
WRITE(2,'(a)') '@map color 9 to (114, 33, 188), "indigo"'
WRITE(2,'(a)') '@map color 10 to (103, 7, 72), "maroon"'
WRITE(2,'(a)') '@map color 11 to (64, 224, 208), "turquoise"'
WRITE(2,'(a)') '@map color 12 to (0, 139, 0), "green4"'
WRITE(2,'(a)') '@map color 13 to (252, 233, 79), "Butter 1"'
WRITE(2,'(a)') '@map color 14 to (237, 212, 0), "Butter 2"'
WRITE(2,'(a)') '@map color 15 to (196, 160, 0), "Butter 3"'
WRITE(2,'(a)') '@map color 16 to (138, 226, 52), "Chameleon 1"'
WRITE(2,'(a)') '@map color 17 to (115, 210, 22), "Chameleon 2"'
WRITE(2,'(a)') '@map color 18 to (78, 154, 6), "Chameleon 3"'
WRITE(2,'(a)') '@map color 19 to (252, 175, 62), "Orange 1"'
WRITE(2,'(a)') '@map color 20 to (245, 121, 0), "Orange 2"'
WRITE(2,'(a)') '@map color 21 to (206, 92, 0), "Orange 3"'
WRITE(2,'(a)') '@map color 22 to (114, 159, 207), "Sky Blue 1"'
WRITE(2,'(a)') '@map color 23 to (52, 101, 164), "Sky Blue 2"'
WRITE(2,'(a)') '@map color 24 to (32, 74, 135), "Sky Blue 3"'
WRITE(2,'(a)') '@map color 25 to (173, 127, 168), "Plum 1"'
WRITE(2,'(a)') '@map color 26 to (117, 80, 123), "Plum 2"'
WRITE(2,'(a)') '@map color 27 to (92, 53, 102), "Plum 3"'
WRITE(2,'(a)') '@map color 28 to (233, 185, 110), "Chocolate 1"'
WRITE(2,'(a)') '@map color 29 to (193, 125, 17), "Chocolate 2"'
WRITE(2,'(a)') '@map color 30 to (143, 89, 2), "Chocolate 3"'
WRITE(2,'(a)') '@map color 31 to (239, 41, 41), "Scarlet Red 1"'
WRITE(2,'(a)') '@map color 32 to (204, 0, 0), "Scarlet Red 2"'
WRITE(2,'(a)') '@map color 33 to (164, 0, 0), "Scarlet Red 3"'
WRITE(2,'(a)') '@map color 34 to (238, 238, 236), "Aluminium 1"'
WRITE(2,'(a)') '@map color 35 to (211, 215, 207), "Aluminium 2"'
WRITE(2,'(a)') '@map color 36 to (186, 189, 182), "Aluminium 3"'
WRITE(2,'(a)') '@map color 37 to (136, 138, 133), "Aluminium 4"'
WRITE(2,'(a)') '@map color 38 to (85, 87, 83), "Aluminium 5"'
WRITE(2,'(a)') '@map color 39 to (46, 52, 54), "Aluminium 6"'
WRITE(2,'(a)') '@reference date 0'
WRITE(2,'(a)') '@date wrap off'
WRITE(2,'(a)') '@date wrap year 1950'
WRITE(2,'(a)') '@default linewidth 1.0'
WRITE(2,'(a)') '@default linestyle 1'
WRITE(2,'(a)') '@default color 1'
WRITE(2,'(a)') '@default pattern 1'
WRITE(2,'(a)') '@default font 0'
WRITE(2,'(a)') '@default char size 1.000000'
WRITE(2,'(a)') '@default symbol size 1.000000'
WRITE(2,'(a)') '@default sformat "%.8g"'
WRITE(2,'(a)') '@background color 0'
WRITE(2,'(a)') '@page background fill on'
WRITE(2,'(a)') '@timestamp off'
WRITE(2,'(a)') '@timestamp 0.03, 0.03'
WRITE(2,'(a)') '@timestamp color 1'
WRITE(2,'(a)') '@timestamp rot 0'
WRITE(2,'(a)') '@timestamp font 0'
WRITE(2,'(a)') '@timestamp char size 1.000000'
!WRITE(2,'(a)') '@timestamp def "Mon Aug 27 21:59:15 2018"'
WRITE(2,'(a)') '@r0 off'
WRITE(2,'(a)') '@link r0 to g0'
WRITE(2,'(a)') '@r0 type above'
WRITE(2,'(a)') '@r0 linestyle 1'
WRITE(2,'(a)') '@r0 linewidth 1.0'
WRITE(2,'(a)') '@r0 color 1'
WRITE(2,'(a)') '@r0 line 0, 0, 0, 0'
WRITE(2,'(a)') '@r1 off'
WRITE(2,'(a)') '@link r1 to g0'
WRITE(2,'(a)') '@r1 type above'
WRITE(2,'(a)') '@r1 linestyle 1'
WRITE(2,'(a)') '@r1 linewidth 1.0'
WRITE(2,'(a)') '@r1 color 1'
WRITE(2,'(a)') '@r1 line 0, 0, 0, 0'
WRITE(2,'(a)') '@r2 off'
WRITE(2,'(a)') '@link r2 to g0'
WRITE(2,'(a)') '@r2 type above'
WRITE(2,'(a)') '@r2 linestyle 1'
WRITE(2,'(a)') '@r2 linewidth 1.0'
WRITE(2,'(a)') '@r2 color 1'
WRITE(2,'(a)') '@r2 line 0, 0, 0, 0'
WRITE(2,'(a)') '@r3 off'
WRITE(2,'(a)') '@link r3 to g0'
WRITE(2,'(a)') '@r3 type above'
WRITE(2,'(a)') '@r3 linestyle 1'
WRITE(2,'(a)') '@r3 linewidth 1.0'
WRITE(2,'(a)') '@r3 color 1'
WRITE(2,'(a)') '@r3 line 0, 0, 0, 0'
WRITE(2,'(a)') '@r4 off'
WRITE(2,'(a)') '@link r4 to g0'
WRITE(2,'(a)') '@r4 type above'
WRITE(2,'(a)') '@r4 linestyle 1'
WRITE(2,'(a)') '@r4 linewidth 1.0'
WRITE(2,'(a)') '@r4 color 1'
WRITE(2,'(a)') '@r4 line 0, 0, 0, 0'
end SUBROUTINE


