SUBROUTINE help_me()
  write(*,"(A)")"----------------------------------------------------------------------------------------------------------------------------------------"
  write(*,"(A)")"                                                  ## Command-line Options: ##"
  write(*,"(A)")"----------------------------------------------------------------------------------------------------------------------------------------"
  write(*,"(A)")"Elatools.x -d [Integer] -m [Integer/String] -ewp [String]  -ktc [String]   -op [String]"
  write(*,"(A)")"            |            |                    |              |              |           "
  write(*,"(A)")"            |            |                    |              |              ^           "
  write(*,"(A)")"            |            |                    |              |       Type of 2D system  " 
  write(*,"(A)")"            |            |                    |              |       2D: def => Default option| adv => Advanced option"
  write(*,"(A)")"            |            |                    |              ^                          "
  write(*,"(A)")"            |            |                    |   Calculate Min. thermal conductivity   "
  write(*,"(A)")"            |            |                    |   3D: y => Yes| n => No                 "
  write(*,"(A)")"            |            |                    ^                                         " 
  write(*,"(A)")"            |            |    Calculate elastic wave properties                         "
  write(*,"(A)")"            |            |    3D: y => Yes| n => No                                     " 
  write(*,"(A)")"            |            ^                                                              "
  write(*,"(A)")"            |       Output code                                                         "  
  write(*,"(A)")"            |       3D: 1 => IRelast| 2 => Elast| 3 => AELAS| 4 => ElaStic| 5 => Cij file| 6 => offline Databank|  7 => online Databank "                                
  write(*,"(A)")"            |       2D: 1 => AELAS  | 2 => IRelast2D| 3 => Cij-2D file  "
  write(*,"(A)")"            ^"       
  write(*,"(A)")"       System Type                                                                      "
  write(*,"(A)")"       3 => 3D sys. and 2 => 2D sys."
  write(*,"(A)")""
  write(*,"(A)")"----------------------------------------------------------------------------------------------------------------------------------------"

  write(*,"(A)")" > Example for 3D system:"
  write(*,"(A)")" Elatools.x -d 3 -m 5"
  write(*,"(A)")" Elatools.x -d 3 -m 3 -ewp y"
  write(*,"(A)")" Elatools.x -d 3 -m 1 -ewp y -ktc y"
  write(*,"(A)")""
  write(*,"(A)")" > Example for 2D system:"
  write(*,"(A)")" Elatools.x -d 2 -m 2 -op def"
  write(*,"(A)")" Elatools.x -d 2 -m 3 -op adv"

END SUBROUTINE
