
!```````````````````````````````````````````````````````````````````````````````````````````
! Copyright (c) 2018 Shahram Yalameha <yalameha93@gmail.com> , <sh.yalameha@sci.ui.ac.ir>, `
!               Please report bugs or suggestions to:  yalameha93@gmail.com                `
!                                                                                          `
!```````````````````````````````````````````````````````````````````````````````````````````
SUBROUTINE stitle_web()
  IMPLICIT NONE
  WRITE(66,"(3a)")'<h1> Generated by ElATools (c) 2021 </h1>'
  WRITE(66,"(a)")'<div class="plot3D">'
END SUBROUTINE
!===============================
SUBROUTINE start_layout_web()
  IMPLICIT NONE
 WRITE(66,"(a)")'<div id="Elatools" style="width: 600px; height: 600px; display:block;" class="js-plotly-plot">'
 WRITE(66,"(a)")'<script type="text/javascript">'
 
  END SUBROUTINE
