
!```````````````````````````````````````````````````````````````````````````````````````````
! Copyright (c) 2018 Shahram Yalameha <yalameha93@gmail.com> , <sh.yalameha@sci.ui.ac.ir>, `
!               Please report bugs or suggestions to:  yalameha93@gmail.com                `
!                                                                                          `
!```````````````````````````````````````````````````````````````````````````````````````````
SUBROUTINE   end_layout_web(namepro,width,height)
  IMPLICIT NONE 
        integer                          :: height,width
        ChARACTER(len=30)                :: title 
        ChARACTER(len=10)                :: namepro 
     if (namepro == "poi"  )    title="Poisson\'s ratio"
     if (namepro == "pugh"  )    title="Pugh\'s ratio"
     if (namepro == "young")    title="Young\'s modulus"
     if (namepro == "bulk")    title="Bulk modulus"
     if (namepro == "shear")    title="Shear modulus"
     if (namepro == "comp" )    title="Linear compressibility"
     if (namepro == "hard" )    title="Hardness"
     if (namepro == "pp" )    title="P-mode of Phase velocity"
     if (namepro == "pf" )    title="SF-mode of Phase velocity"
     if (namepro == "ps" )    title="SS-mode of Phase velocity"
     if (namepro == "gp" )    title="P-mode of Group velocity"
     if (namepro == "gf" )    title="SF-mode of Group velocity"
     if (namepro == "gs" )    title="SS-mode of Group velocity"

     if (namepro == "pfp" )    title="Power Flow angle P-mode"
     if (namepro == "pff" )    title="Power Flow angle Fast-mode"
     if (namepro == "pfs" )    title="Power Flow angle Slow-mode"
     if (namepro == "km" )    title="Min. thermal conductivity"
     
    WRITE(66,"(a)")"var layout ="
    WRITE(66,"(a)")"{"
    WRITE(66,"(3a)")"   title: '",title,"',"
    WRITE(66,"(3a)")"   font: {family: 'Balto', size: 15 },"
    WRITE(66,"(3a)")"   scene: {"
	   WRITE(66,"(3a)")"	  xaxis:{title: 'X', font: { family: 'Balto', size: 18,  color: 'black' }, gridwidth:2.0 },"
    WRITE(66,"(3a)")"		  yaxis:{title: 'Y', font: { family: 'Balto', size: 18,  color: 'black' }, gridwidth:2.0 },"
    WRITE(66,"(3a)")"	  	zaxis:{title: 'Z', font: { family: 'Balto', size: 18,  color: 'black' }, gridwidth:2.0 },"
    WRITE(66,"(3a)")"		},"
    WRITE(66,"(a,I7,a)")"   width: ",width,","
    WRITE(66,"(a,I7,a)")"   height: ",height,","
    WRITE(66,"(a)")"   autosize: true,"
    WRITE(66,"(a)")"   autorange: true,"
    WRITE(66,"(a)")"   margin: {l: 65, r: 50, b: 65, t: 90}"
    WRITE(66,"(a)")"};"
    WRITE(66,"(a)")"Plotly.newPlot('Elatools',data,layout);"
    WRITE(66,"(a)")"</script>  " 
 END SUBROUTINE   
 
SUBROUTINE   end_polarlayout_web(namepro,width,height)
  IMPLICIT NONE 
        integer                          :: height,width
        ChARACTER(len=30)                :: title 
        ChARACTER(len=10)                :: namepro 
     if (namepro == "poi2d"  )    title="Poisson\'s ratio"
     if (namepro == "pugh2d"  )    title="Pugh\'s ratio"
     if (namepro == "young2d")    title="Young\'s modulus"
     if (namepro == "bulk2d")    title="Bulk modulus"
     if (namepro == "shear2d")    title="Shear modulus"
     if (namepro == "com2d" )    title="Linear compressibility"
     if (namepro == "hard2d" )    title="Hardness"
     if (namepro == "pp2d" )    title="P-mode of Phase velocity"
     if (namepro == "pf2d" )    title="SF-mode of Phase velocity"
     if (namepro == "ps2d" )    title="SS-mode of Phase velocity"
     if (namepro == "gp2d" )    title="P-mode of Group velocity"
     if (namepro == "gf2d" )    title="SF-mode of Group velocity"
     if (namepro == "gs2d" )    title="SS-mode of Group velocity"

     if (namepro == "pfp2d" )    title="Power Flow P-mode"
     if (namepro == "pff2d" )    title="Power Flow Fast-mode"
     if (namepro == "pfs2d" )    title="Power Flow Slow-mode"
     if (namepro == "km2d" )     title="Min. thermal conductivity"
     
    WRITE(66,"(a)")"var layout ="
    WRITE(66,"(a)")"{"
    WRITE(66,"(3a)")"   title: '",title,"',"
    WRITE(66,"(3a)")"   font: {family: 'Balto', size: 18 },"
    WRITE(66,"(3a)")"   updatemenus: updatemenus, "
    WRITE(66,"(a,I7,a)")"   width: ",width,","
    WRITE(66,"(a,I7,a)")"   height: ",height,","
     WRITE(66,"(a,I7,a)")" polar: { radialaxis: {  visible: true, autorange: true } },"
    WRITE(66,"(a)")"};"
    WRITE(66,"(a)")"Plotly.newPlot('Elatools',data,layout);"
    WRITE(66,"(a)")"</script>  " 
 END SUBROUTINE    
 !==================================================================================
 SUBROUTINE   buttone_polar_web(max_value)
  IMPLICIT NONE 
        integer                          :: height,width
        ChARACTER(len=30)                :: title 
        ChARACTER(len=10)                :: namepro 
        DOUBLE PRECISION                 :: max_value            
     if (namepro == "poi2d"  )    title="Poisson\'s ratio"
     if (namepro == "pugh2d"  )    title="Pugh\'s ratio"
     if (namepro == "young2d")    title="Young\'s modulus"
     if (namepro == "bulk2d")    title="Bulk modulus"
     if (namepro == "shear2d")    title="Shear modulus"
     if (namepro == "com2d" )    title="Linear compressibility"
     if (namepro == "hard2d" )    title="Hardness"
     if (namepro == "pp2d" )    title="P-mode of Phase velocity"
     if (namepro == "pf2d" )    title="SF-mode of Phase velocity"
     if (namepro == "ps2d" )    title="SS-mode of Phase velocity"
     if (namepro == "gp2d" )    title="P-mode of Group velocity"
     if (namepro == "gf2d" )    title="SF-mode of Group velocity"
     if (namepro == "gs2d" )    title="SS-mode of Group velocity"

     if (namepro == "pfp2d" )    title="Power Flow angle P-mode"
     if (namepro == "pff2d" )    title="Power Flow angle Slow-mode"
     if (namepro == "pfs2d" )    title="Group velocity Fast-mode"
     if (namepro == "km2d"  )    title="Min. thermal conductivity"
     
    WRITE(66,"(a)")" "
    WRITE(66,"(a)")"var updatemenus=["
    WRITE(66,"(a)")"    {"
    WRITE(66,"(a)")"        buttons: ["
    WRITE(66,"(a)")"            {"
    WRITE(66,"(a)")"                args: [ {'visible': [true]},"
    WRITE(66,"(a)")"                        {'polar': {'angularaxis': {'color':'black','showgrid': [true],'ticks':'inside','tickwidth':2} ,"
    WRITE(66,"(a)")"                        'bgcolor':'#FDFDFD',"
    WRITE(66,"(a)")"                        'radialaxis':{'tickangle':90, 'autorange':[true]},"
    WRITE(66,"(a)")"                        'sector': [0, 90] } "
    WRITE(66,"(a)")"                        }],"
    WRITE(66,"(a)")"                label:'Sector 90',"
    WRITE(66,"(a)")"                method:'update',"
    WRITE(66,"(a)")"            },"
    WRITE(66,"(a)")"            {"
    WRITE(66,"(a)")"                args: [ {'visible': [true]}, "
    WRITE(66,"(a)")"                        {'polar': {'angularaxis': {'color':'black','showgrid': [true],'ticks':'inside','tickwidth':2} ,"
    WRITE(66,"(a)")"                        'bgcolor':'#FDFDFD',"
    WRITE(66,"(a)")"                        'radialaxis':{'tickangle':90, 'autorange':[true]},"
    WRITE(66,"(a)")"                        'sector': [0, 180] } "
    WRITE(66,"(a)")"                        },{'line':{'color': 'red'}}],"
    WRITE(66,"(a)")"                label: 'Sector 180',"
    WRITE(66,"(a)")"                method: 'update'"
    WRITE(66,"(a)")"            },"
    WRITE(66,"(a)")"           {"
    WRITE(66,"(a)")"                args: [ {'visible': [true]},"
    WRITE(66,"(a)")"                        {'polar': {'angularaxis': {'color':'black','showgrid': [true],'ticks':'inside','tickwidth':2} ,"
    WRITE(66,"(a)")"                        'bgcolor':'#FDFDFD',"
    WRITE(66,"(a)")"                        'radialaxis':{'tickangle':90, 'autorange':[true]},"
    WRITE(66,"(a)")"                        'sector': [0, 360] } "
    WRITE(66,"(a)")"                        }],"
    WRITE(66,"(a)")"                label:'Sector 360',"
    WRITE(66,"(a)")"                method:'update',"
    WRITE(66,"(a)")"            },"
    WRITE(66,"(a)")"        ],"
    WRITE(66,"(a)")"         x: 0.2,"
    WRITE(66,"(a)")"        y: 1.25,"
    WRITE(66,"(a)")"        xref: 'paper',"
    WRITE(66,"(a)")"        yref: 'paper',"
    WRITE(66,"(a)")"        active: 0,"
    WRITE(66,"(a)")"    },"
    
    WRITE(66,"(a)")"    {"
    WRITE(66,"(a)")"        buttons: ["
    WRITE(66,"(a)")"            {"
    WRITE(66,"(a)")"                args: [ {'visible': [true]},"
    WRITE(66,"(a)")"                        {'polar': {'angularaxis': {'color':'black','showgrid': [true],'ticks':'inside','tickwidth':2} ,"
    WRITE(66,"(a)")"                        'bgcolor':'#FDFDFD',"
    WRITE(66,"(a,F15.7,a)")"                        'radialaxis':{'tickangle':90, 'range':[0,",max_value*1.1,"]},"
    WRITE(66,"(a)")"                        'sector': [0, 360] } "
    WRITE(66,"(a)")"                        }],"
    WRITE(66,"(a)")"                label:'Zoom x1.1',"
    WRITE(66,"(a)")"                method:'update',"
    WRITE(66,"(a)")"            },"
    WRITE(66,"(a)")"            {"
    WRITE(66,"(a)")"                args: [ {'visible': [true]}, "
    WRITE(66,"(a)")"                        {'polar': {'angularaxis': {'color':'black','showgrid': [true],'ticks':'inside','tickwidth':2} ,"
    WRITE(66,"(a)")"                        'bgcolor':'#FDFDFD',"
    WRITE(66,"(a,F15.7,a)")"                        'radialaxis':{'tickangle':90, 'range':[0,",max_value*1.2,"]},"
    WRITE(66,"(a)")"                        'sector': [0, 360] } "
    WRITE(66,"(a)")"                        },{'line':{'color': 'red'}}],"
    WRITE(66,"(a)")"                label: 'Zoom x1.2',"
    WRITE(66,"(a)")"                method: 'update'"
    WRITE(66,"(a)")"            },"
    WRITE(66,"(a)")"           {"
    WRITE(66,"(a)")"                args: [ {'visible': [true]},"
    WRITE(66,"(a)")"                        {'polar': {'angularaxis': {'color':'black','showgrid': [true],'ticks':'inside','tickwidth':2} ,"
    WRITE(66,"(a)")"                        'bgcolor':'#FDFDFD',"
    WRITE(66,"(a,F15.7,a)")"                        'radialaxis':{'tickangle':90, 'range':[0,",max_value*1.3,"]},"
    WRITE(66,"(a)")"                        'sector': [0, 360] } "
    WRITE(66,"(a)")"                        }],"
    WRITE(66,"(a)")"                label:'Zoom x1.3',"
    WRITE(66,"(a)")"                method:'update',"
    WRITE(66,"(a)")"            },"
    WRITE(66,"(a)")"        ],"
    WRITE(66,"(a)")"         x: 0.2,"
    WRITE(66,"(a)")"        y: 1.15,"
    WRITE(66,"(a)")"        xref: 'paper',"
    WRITE(66,"(a)")"        yref: 'paper',"
    WRITE(66,"(a)")"        active: 0,"
    WRITE(66,"(a)")"    }"    
    WRITE(66,"(a)")"]"
 END SUBROUTINE    
