
!```````````````````````````````````````````````````````````````````````````````````````````
! Copyright (c) 2018 Shahram Yalameha <yalameha93@gmail.com> , <sh.yalameha@sci.ui.ac.ir>, `
!               Please report bugs or suggestions to:  yalameha93@gmail.com                `
!                                                                                          `
!```````````````````````````````````````````````````````````````````````````````````````````
SUBROUTINE end_layout_web(namepro, width, height)
   IMPLICIT NONE
   integer                          :: height, width
   ChARACTER(len=38)                :: title
   ChARACTER(len=10)                :: namepro
   if (namepro == "poi") title = "Poisson\'s ratio"
   if (namepro == "pugh") title = "Pugh\'s ratio"
   if (namepro == "young") title = "Young\'s modulus"
   if (namepro == "bulk") title = "Bulk modulus"
   if (namepro == "shear") title = "Shear modulus"
   if (namepro == "comp") title = "Linear compressibility"
   if (namepro == "hard") title = "Hardness"
   if (namepro == "pp") title = "P-mode of Phase velocity"
   if (namepro == "pf") title = "SF-mode of Phase velocity"
   if (namepro == "ps") title = "SS-mode of Phase velocity"
   if (namepro == "gp") title = "P-mode of Group velocity"
   if (namepro == "gf") title = "SF-mode of Group velocity"
   if (namepro == "gs") title = "SS-mode of Group velocity"

   if (namepro == "pfp") title = "Power Flow angle P-mode"
   if (namepro == "pff") title = "Power Flow angle Fast-mode"
   if (namepro == "pfs") title = "Power Flow angle Slow-mode"
   if (namepro == "km") title = "Min. thermal conductivity"

   if (namepro == "you3ds") title = "3D-Slice of Young\'s modulus"
   if (namepro == "bulk3ds") title = "3D-Slice of Bulk modulus"
   if (namepro == "poi3ds") title = "3D-Slice of Poisson\'s ratio"
   if (namepro == "comp3ds") title = "3D-Slice of Linear compressibility"
   if (namepro == "pugh3ds") title = "3D-Slice of Phug\'s ratio"
   if (namepro == "she3ds") title = "3D-Slice of Shear modulus"
   if (namepro == "hard3ds") title = "3D-Slice of Hardness"
   if (namepro == "pp3ds") title = "3D-Slice of Phase velocity: P-mode"
   if (namepro == "pf3ds") title = "3D-Slice of Phase velocity: F-mode"
   if (namepro == "ps3ds") title = "3D-Slice of Phase velocity: S-mode"
   if (namepro == "gp3ds") title = "3D-Slice of Group velocity: P-mode"
   if (namepro == "gf3ds") title = "3D-Slice of Group velocity: F-mode"
   if (namepro == "gs3ds") title = "3D-Slice of Group velocity: S-mode"
   if (namepro == "pfp3ds") title = "3D-Slice of Power Flow angle: P-mode"
   if (namepro == "pff3ds") title = "3D-Slice of Power Flow angle: F-mode"
   if (namepro == "pfs3ds") title = "3D-Slice of Power Flow angle: S-mode"

   if (namepro == "pa3ds") title = "3D-Slice of Phase velocities"
   if (namepro == "ga3ds") title = "3D-Slice of Group velocities"
   if (namepro == "pfa3ds") title = "3D-Slice of Power Flow angles"
   if (namepro == "km3ds") title = "3D-Slice of Min. thermal conductivity"

   WRITE (66, "(a)") "var layout ="
   WRITE (66, "(a)") "{"
   WRITE (66, "(3a)") "   title: { text:' ", title, "',"
   WRITE (66, "(3a)") "            font: { family: 'Arial, sans-serif', size: 22, color: '#ffffff' },"
   WRITE (66, "(3a)") "            y: 0.95"
   WRITE (66, "(3a)") "},"
   WRITE (66, "(3a)") "   scene: {"
   WRITE (66, "(3a)") "         xaxis: { title: 'X Axis', titlefont: { family: 'Arial, sans-serif', size: 16, color: '#ffffff' },&
                                tickfont: { family: 'Arial, sans-serif', size: 13, color: '#cccccc' }, gridcolor: '#444444', zerolinecolor: '#777777' },"
   WRITE (66, "(3a)") "         yaxis: { title: 'Y Axis', titlefont: { family: 'Arial, sans-serif', size: 16, color: '#ffffff' },&
                                tickfont: { family: 'Arial, sans-serif', size: 13, color: '#cccccc' }, gridcolor: '#444444', zerolinecolor: '#777777' },"
   WRITE (66, "(3a)") "         zaxis: { title: 'Z Axis', titlefont: { family: 'Arial, sans-serif', size: 16, color: '#ffffff' },&
                                tickfont: { family: 'Arial, sans-serif', size: 13, color: '#cccccc' }, gridcolor: '#444444', zerolinecolor: '#777777' },"
   WRITE (66, "(3a)") "         camera: { eye: { x: 1.5, y: 1.5, z: 1.2 } },"
   WRITE (66, "(3a)") "         aspectratio: { x: 1, y: 1, z: 0.8 }"
   WRITE (66, "(3a)") "},"
   WRITE (66, "(3a)") "    autosize: true,"
   WRITE (66, "(3a)") "    margin: { l: 20, r: 20, b: 40, t: 80 },"
   WRITE (66, "(3a)") "    paper_bgcolor: 'transparent',"
   WRITE (66, "(3a)") "    plot_bgcolor: 'transparent'"
  ! WRITE (66, "(a,I7,a)") "   width: ", width, ","
  ! WRITE (66, "(a,I7,a)") "   height: ", height, ","   
   WRITE (66, "(3a)") "};"

   WRITE (66, "(3a)") "   var config = { responsive: true, displayModeBar: true };"

 
   WRITE (66, "(3a)") "   Plotly.newPlot('Elatools', data, layout, config);"
   WRITE (66, "(3a)") "</script>  "
   WRITE (66, "(3a)") "  "
   WRITE (66, "(3a)") "</body>"
   WRITE (66, "(3a)") "</html>"

!   WRITE (66, "(a)") "   autosize: true,"
!   WRITE (66, "(a)") "   autorange: true,"
!   WRITE (66, "(a)") "   margin: {l: 65, r: 50, b: 65, t: 90}"
!   WRITE (66, "(a)") "};"
!   WRITE (66, "(a)") "Plotly.newPlot('Elatools',data,layout);"
!   WRITE (66, "(a)") "</script>  "
END SUBROUTINE

SUBROUTINE end_polarlayout_web(namepro, width, height)
   IMPLICIT NONE
   integer                          :: height, width
   ChARACTER(len=30)                :: title
   ChARACTER(len=10)                :: namepro
   if (namepro == "poi2d") title = "Poisson\'s ratio"
   if (namepro == "pugh2d") title = "Pugh\'s ratio"
   if (namepro == "young2d") title = "Young\'s modulus"
   if (namepro == "bulk2d") title = "Bulk modulus"
   if (namepro == "shear2d") title = "Shear modulus"
   if (namepro == "com2d") title = "Linear compressibility"
   if (namepro == "hard2d") title = "Hardness"
   if (namepro == "pp2d") title = "P-mode of Phase velocity"
   if (namepro == "pf2d") title = "SF-mode of Phase velocity"
   if (namepro == "ps2d") title = "SS-mode of Phase velocity"
   if (namepro == "gp2d") title = "P-mode of Group velocity"
   if (namepro == "gf2d") title = "SF-mode of Group velocity"
   if (namepro == "gs2d") title = "SS-mode of Group velocity"

   if (namepro == "pfp2d") title = "Power Flow P-mode"
   if (namepro == "pff2d") title = "Power Flow Fast-mode"
   if (namepro == "pfs2d") title = "Power Flow Slow-mode"
   if (namepro == "km2d") title = "Min. thermal conductivity"
   if (namepro == '2dyoung' .or. namepro == '2dyou' .or. namepro == '2dYoung') title = "Young\'s modulus"
   if (namepro == "2dshear" .or. namepro == "2dshe") title = "Shear modulus"
   if (namepro == "2dpoi" .or. namepro == "2dpoisson") title = "Poisson\'s ratio"
   
   if (namepro == "2dlong" .or. namepro == "2dLong") title = "Transverse Wave"
   if (namepro == "2dtran" .or. namepro == "2dTran") title = "Longitudinal Wave"
  ! WRITE (66, "(a)") "var layout ="
  ! WRITE (66, "(a)") "{"
  ! WRITE (66, "(3a)") "   title: '", title, "',"
  ! WRITE (66, "(3a)") "   font: {family: 'Balto', size: 18 },"
  ! WRITE (66, "(3a)") "   updatemenus: updatemenus, "
  ! WRITE (66, "(a,I7,a)") "   width: ", width, ","
  ! WRITE (66, "(a,I7,a)") "   height: ", height, ","
   !WRITE (66, "(a,I7,a)") " polar: { radialaxis: {  visible: true, autorange: true } },"
   !WRITE (66, "(a)") "};"
   !WRITE (66, "(a)") "Plotly.newPlot('Elatools',data,layout);"
   !WRITE (66, "(a)") "</script>  "

   WRITE (66, "(a)") "var layout = {"
   WRITE (66, "(3a)") '            title: { text: "<b>', title, '</b>",' 
   !WRITE (66, "(a)") "            title: { "
   !WRITE (66, "(a)") "                text: "<b>Poisson's Ratio (2D Cut)</b>","
   WRITE (66, "(a)") "                font: { family: 'Arial, sans-serif', size: 22, color: '#ffffff' },"
   WRITE (66, "(a)") "                y: 0.95"
   WRITE (66, "(a)") "            },"
   WRITE (66, "(a)") "            updatemenus: updatemenus,"
   WRITE (66, "(a,I7,a)") "            width: ", width, ","
   WRITE (66, "(a,I7,a)") "            height: ", height, ","   
   WRITE (66, "(a)") "            polar: { "
   WRITE (66, "(a)") "                bgcolor: 'transparent',"
   WRITE (66, "(a)") "                angularaxis: { "
   WRITE (66, "(a)") "                    color: '#ffffff', // Axis text color"
   WRITE (66, "(a)") "                    tickfont: { size: 14, color: '#cccccc' }, "
   WRITE (66, "(a)") "                    gridcolor: '#444444', "
   WRITE (66, "(a)") "                    linecolor: '#777777' "
   WRITE (66, "(a)") "                },"
   WRITE (66, "(a)") "                radialaxis: { "
   WRITE (66, "(a)") "                    visible: true, "
   WRITE (66, "(a)") "                    autorange: true,"
   WRITE (66, "(a)") "                    color: '#ffffff',"
   WRITE (66, "(a)") "                    tickfont: { size: 14, color: '#cccccc' }, "
   WRITE (66, "(a)") "                    gridcolor: '#444444', "
   WRITE (66, "(a)") "                    linecolor: '#777777',"
   WRITE (66, "(a)") "                    tickangle: 90"
   WRITE (66, "(a)") "                }"
   WRITE (66, "(a)") "            },"
   WRITE (66, "(a)") "            legend: {"
   WRITE (66, "(a)") "                font: { family: 'Arial, sans-serif', size: 14, color: '#ffffff' },"
   WRITE (66, "(a)") "                bgcolor: 'rgba(0,0,0,0)', // Transparent legend background"
   WRITE (66, "(a)") "                bordercolor: '#444444',"
   WRITE (66, "(a)") "                borderwidth: 1"
   WRITE (66, "(a)") "            },"
   WRITE (66, "(a)") "            autosize: true,"
   WRITE (66, "(a)") "            margin: { l: 40, r: 40, b: 40, t: 120 },"
   WRITE (66, "(a)") "            paper_bgcolor: 'transparent',"
   WRITE (66, "(a)") "            plot_bgcolor: 'transparent'"
   WRITE (66, "(a)") "        };"

   WRITE (66, "(a)") "        var config = { responsive: true, displayModeBar: true };"
        
   WRITE (66, "(a)") "        Plotly.newPlot('Elatools', data, layout, config);"
   WRITE (66, "(a)") "    </script>  "
   WRITE (66, "(a)") "</body>"
   WRITE (66, "(a)") "</html>   "
   
END SUBROUTINE
!==================================================================================
SUBROUTINE buttone_polar_web(max_value)
   IMPLICIT NONE
   integer                          :: height, width
   ChARACTER(len=30)                :: title
   ChARACTER(len=10)                :: namepro
   DOUBLE PRECISION                 :: max_value
   if (namepro == "poi2d" .or. namepro == "2dpoi") title = "Poisson\'s ratio"
   if (namepro == "pugh2d") title = "Pugh\'s ratio"
   if (namepro == "young2d" .or. namepro == "2dyoung") title = "Young\'s modulus"
   if (namepro == "bulk2d") title = "Bulk modulus"
   if (namepro == "shear2d" .or. namepro == "2dshear") title = "Shear modulus"
   if (namepro == "com2d") title = "Linear compressibility"
   if (namepro == "hard2d") title = "Hardness"
   if (namepro == "pp2d") title = "P-mode of Phase velocity"
   if (namepro == "pf2d") title = "SF-mode of Phase velocity"
   if (namepro == "ps2d") title = "SS-mode of Phase velocity"
   if (namepro == "gp2d") title = "P-mode of Group velocity"
   if (namepro == "gf2d") title = "SF-mode of Group velocity"
   if (namepro == "gs2d") title = "SS-mode of Group velocity"

   if (namepro == "pfp2d") title = "Power Flow angle P-mode"
   if (namepro == "pff2d") title = "Power Flow angle Slow-mode"
   if (namepro == "pfs2d") title = "Group velocity Fast-mode"
   if (namepro == "km2d") title = "Min. thermal conductivity"

   if (namepro == '2dyoung' .or. namepro == '2dyou' .or. namepro == '2dYoung') title = "Young\'s modulus"
   if (namepro == "2dshear" .or. namepro == "2dshe") title = "Shear modulus"
   if (namepro == "2dpoi" .or. namepro == "2dpoisson") title = "Poisson\'s ratio"
   
   if (namepro == "2dlong" .or. namepro == "2dLong") title = "Transverse Wave"
   if (namepro == "2dtran" .or. namepro == "2dTran") title = "Longitudinal Wave"

   WRITE (66, "(a)") " "
   WRITE (66, "(a)") "var updatemenus=["
   WRITE (66, "(a)") "    {"
   WRITE (66, "(a)") "        buttons: ["
   WRITE (66, "(a)") "            {"
   WRITE (66, "(a)") "             args: [{}, {'polar.sector': [0, 90], 'polar.radialaxis.autorange': true}],"
   WRITE (66, "(a)") "             label: 'Sector 90°',"
   WRITE (66, "(a)") "             method: 'update',"
   WRITE (66, "(a)") "            },"
   WRITE (66, "(a)") "            {"
   WRITE (66, "(a)") "             args: [{}, {'polar.sector': [0, 180], 'polar.radialaxis.autorange': true}],"
   WRITE (66, "(a)") "             label: 'Sector 180°',"
   WRITE (66, "(a)") "             method: 'update',"
   WRITE (66, "(a)") "            },"
   WRITE (66, "(a)") "           {"
   WRITE (66, "(a)") "             args: [{}, {'polar.sector': [0, 360], 'polar.radialaxis.autorange': true}],"
   WRITE (66, "(a)") "             label: 'Sector 360°',"
   WRITE (66, "(a)") "             method: 'update',"
   WRITE (66, "(a)") "            },"
   WRITE (66, "(a)") "        ],"
   WRITE (66, "(a)") "         direction: 'down',"
   WRITE (66, "(a)") "         showactive: true,"
   WRITE (66, "(a)") "         x: 0.2,"
   WRITE (66, "(a)") "         y: 1.25,"
   WRITE (66, "(a)") "         xref: 'paper',"
   WRITE (66, "(a)") "         yref: 'paper',"
  ! WRITE (66, "(a)") "        active: 0,"
   WRITE (66, "(a)") "        active: 2,"
   WRITE (66, "(a)") "        font: { color: '#ffffff' },"
   WRITE (66, "(a)") "        bgcolor: '#333333',"
   WRITE (66, "(a)") "        bordercolor: '#555555'   "
   WRITE (66, "(a)") "    },"

   WRITE (66, "(a)") "    {"
   WRITE (66, "(a)") "        buttons: ["
   WRITE (66, "(a)") "            {"
   WRITE (66, "(a)") "               args: [{}, {'polar.radialaxis.autorange': false, 'polar.radialaxis.range': [0, 2.6319450]}],"
   WRITE (66, "(a)") "               label: 'Zoom x1.1',"
   WRITE (66, "(a)") "               method: 'update',"
   WRITE (66, "(a)") "            },"
   WRITE (66, "(a)") "            {"
   WRITE (66, "(a)") "               args: [{}, {'polar.radialaxis.autorange': false, 'polar.radialaxis.range': [0, 2.8712127]}],"
   WRITE (66, "(a)") "               label: 'Zoom x1.2',"
   WRITE (66, "(a)") "               method: 'update',"
   WRITE (66, "(a)") "            },"
   WRITE (66, "(a)") "           {"
   WRITE (66, "(a)") "               args: [{}, {'polar.radialaxis.autorange': false, 'polar.radialaxis.range': [0, 3.1104802]}],"
   WRITE (66, "(a)") "               label: 'Zoom x1.3',"
   WRITE (66, "(a)") "               method: 'update',"
   WRITE (66, "(a)") "            },"
   WRITE (66, "(a)") "           {"
   WRITE (66, "(a)") "           args: [{}, {'polar.radialaxis.autorange': true}],"
   WRITE (66, "(a)") "           label: 'Auto Fit',"
   WRITE (66, "(a)") "           method: 'update',"
   WRITE (66, "(a)") "           }"
   WRITE (66, "(a)") "        ],"
   WRITE (66, "(a)") "         x: 0.2,"
   WRITE (66, "(a)") "        y: 1.15,"
   WRITE (66, "(a)") "        xref: 'paper',"
   WRITE (66, "(a)") "        yref: 'paper',"
   !WRITE (66, "(a)") "        active: 0,"
   WRITE (66, "(a)") "        active: 3,"
   WRITE (66, "(a)") "        font: { color: '#ffffff' },"
   WRITE (66, "(a)") "        bgcolor: '#333333',"
   WRITE (66, "(a)") "        bordercolor: '#555555'   "
   WRITE (66, "(a)") "    }"
   WRITE (66, "(a)") "]"
END SUBROUTINE
!=========================
SUBROUTINE end_layout_web_hmap(namepro, minmaxneg, namberlay)
   IMPLICIT NONE
   integer                          :: namberlay
   ChARACTER(len=38)                :: title, mimang
   ChARACTER(len=10)                :: namepro, minmaxneg
   if (namepro == "hmpoi") title = "Poisson\'s ratio"
   if (namepro == "hmpugh") title = "Pugh\'s ratio"
   if (namepro == "hmyoung") title = "Young\'s modulus (GPa)"
   if (namepro == "hmbulk") title = "Bulk modulus (GPa)"
   if (namepro == "hmshear") title = "Shear modulus (GPa)"
   if (namepro == "hmcomp") title = "Linear compressibility (1/TPa)"
   if (namepro == "hmhard") title = "Hardness (GPa)"
   if (namepro == "hmpp") title = "P-mode of Phase velocity"
   if (namepro == "hmpf") title = "SF-mode of Phase velocity"
   if (namepro == "hmps") title = "SS-mode of Phase velocity"
   if (namepro == "hmgp") title = "P-mode of Group velocity"
   if (namepro == "hmgf") title = "SF-mode of Group velocity"
   if (namepro == "hmgs") title = "SS-mode of Group velocity"

   if (namepro == "hmpfp") title = "Power Flow angle P-mode"
   if (namepro == "hmpff") title = "Power Flow angle Fast-mode"
   if (namepro == "hmpfs") title = "Power Flow angle Slow-mode"
   if (namepro == "hmkm") title = "Min. thermal conductivity"



  if (minmaxneg == "max") mimang="Max. Positive:"
  if (minmaxneg == "min") mimang="Min. Positive:"
  if (minmaxneg == "neg") mimang="Negative:"
  if (minmaxneg == "non") mimang=" "  
  
if (namberlay==1) then  
   WRITE (66, "(a)") "    // Layout settings for Heatmap 1"
   WRITE (66, "(a)") "    var layout1 = {                 "
 !  WRITE (66, "(5a)") "        title: '",trim(mimang)," ", trim(title),"',   "
   WRITE (66, "(a)") "       xaxis: {                     "
   WRITE (66, "(a)") "               title: 'θ (Degree)',  "
   WRITE (66, "(a)") "               tickvals: [0, 45, 90, 135, 177.5]," 
   WRITE (66, "(a)") "               ticktext: ['0','45', '90','135', '180'],"
   WRITE (66, "(a)") "               tickfont: {"
   WRITE (66, "(a)") "                          family: 'Times New Roman',"
   WRITE (66, "(a)") "                          size: 18"
   WRITE (66, "(a)") "                         }," 
     WRITE (66, "(a)") "            },"                              
   WRITE (66, "(a)") "       yaxis: {                     "
   WRITE (66, "(a)") "               title: 'ϕ (Degree)',  "
   WRITE (66, "(a)") "               tickvals: [0, 90, 180, 270, 360]," 
   WRITE (66, "(a)") "               ticktext: ['0', '90', '180', '270', '360'],"
   WRITE (66, "(a)") "               tickfont: {"
   WRITE (66, "(a)") "                          family: 'Times New Roman',"
   WRITE (66, "(a)") "                          size: 18"
   WRITE (66, "(a)") "                      },                "   
   WRITE (66, "(a)") "             }," 
   WRITE (66, "(a)") "             autosize: false,"
   WRITE (66, "(a)") "             width: 450,  "
   WRITE (66, "(a)") "             height: 450,"
   
   WRITE (66, "(a)") "    };                                    "
   WRITE (66, "(a)") "    Plotly.newPlot('heatmap1', heatmapData1, layout1);"
endif

if (namberlay==2) then  
   WRITE (66, "(a)") "    // Layout settings for Heatmap 2"
   WRITE (66, "(a)") "    var layout2 = {                 "
!   WRITE (66, "(5a)") "        title: '",trim(mimang)," ", trim(title),"',   "
   WRITE (66, "(a)") "       xaxis: {                     "
   WRITE (66, "(a)") "               title: 'θ (Degree)',  "
   WRITE (66, "(a)") "               tickvals: [0, 45, 90, 135, 177.5]," 
   WRITE (66, "(a)") "               ticktext: ['0','45', '90','135', '180'],"
   WRITE (66, "(a)") "               tickfont: {"
   WRITE (66, "(a)") "                          family: 'Times New Roman',"
   WRITE (66, "(a)") "                          size: 18"
   WRITE (66, "(a)") "                         }," 
     WRITE (66, "(a)") "            },"                              
   WRITE (66, "(a)") "       yaxis: {                     "
   WRITE (66, "(a)") "               title: 'ϕ (Degree)',  "
   WRITE (66, "(a)") "               tickvals: [0, 90, 180, 270, 360]," 
   WRITE (66, "(a)") "               ticktext: ['0', '90', '180', '270', '360'],"
   WRITE (66, "(a)") "               tickfont: {"
   WRITE (66, "(a)") "                          family: 'Times New Roman',"
   WRITE (66, "(a)") "                          size: 18"
   WRITE (66, "(a)") "                      },                "   
   WRITE (66, "(a)") "             }," 
   WRITE (66, "(a)") "             autosize: false,"
   WRITE (66, "(a)") "             width: 450,  "
   WRITE (66, "(a)") "             height: 450,"
     
   WRITE (66, "(a)") "    };                                   "
   WRITE (66, "(a)") "    Plotly.newPlot('heatmap2', heatmapData2, layout2);"
endif
if (namberlay==3) then  
   WRITE (66, "(a)") "    // Layout settings for Heatmap 2"
   WRITE (66, "(a)") "    var layout3 = {                 "
!   WRITE (66, "(5a)") "        title: '",trim(mimang)," ", trim(title),"',   "
   WRITE (66, "(a)") "       xaxis: {                     "
   WRITE (66, "(a)") "               title: 'θ (Degree)',  "
   WRITE (66, "(a)") "               tickvals: [0, 45, 90, 135, 177.5]," 
   WRITE (66, "(a)") "               ticktext: ['0','45', '90','135', '180'],"
   WRITE (66, "(a)") "               tickfont: {"
   WRITE (66, "(a)") "                          family: 'Times New Roman',"
   WRITE (66, "(a)") "                          size: 18"
   WRITE (66, "(a)") "                         }," 
     WRITE (66, "(a)") "            },"                              
   WRITE (66, "(a)") "       yaxis: {                     "
   WRITE (66, "(a)") "               title: 'ϕ (Degree)',  "
   WRITE (66, "(a)") "               tickvals: [0, 90, 180, 270, 360]," 
   WRITE (66, "(a)") "               ticktext: ['0', '90', '180', '270', '360'],"
   WRITE (66, "(a)") "               tickfont: {"
   WRITE (66, "(a)") "                          family: 'Times New Roman',"
   WRITE (66, "(a)") "                          size: 18"
   WRITE (66, "(a)") "                          },                "   
   WRITE (66, "(a)") "             }," 
   WRITE (66, "(a)") "             autosize: false,"
   WRITE (66, "(a)") "             width: 450,  "
   WRITE (66, "(a)") "             height: 450,"
   
   WRITE (66, "(a)") "    };                                   "
   WRITE (66, "(a)") "    Plotly.newPlot('heatmap3', heatmapData3, layout3);"
endif 
END SUBROUTINE

