!-------------------------------------------------------------------------------------------
! Copyright (c) 2018 Shahram Yalameha <yalameha93@gmail.com> , <sh.yalameha@sci.ui.ac.ir>, -
!               Please report bugs or suggestions to:  yalameha93@gmail.com                -
!                                                                                          -
!-------------------------------------------------------------------------------------------
SUBROUTINE swin_web_hmap(namepro)
  IMPLICIT NONE
  ChARACTER(len=10)                :: namepro
  ChARACTER(len=100)                :: set_namepro

   If (namepro == "hmpoi" .or. namepro == "hmpoisson") set_namepro = "Poisson-heamap"
   If (namepro == "hmpug" .or. namepro == "hmpugh") set_namepro = "Pugh-heamap"
   If (namepro == "hmyou" .or. namepro == "hmyoung") set_namepro = "Young-heamap"
   If (namepro == "hmsh" .or. namepro == "hmshear") set_namepro = "Shear-heamap"
   If (namepro == "hmcom" .or. namepro == "hmcomp") set_namepro = "Compressibility-heamap"
   If (namepro == "hmbul" .or. namepro == "hmbulk") set_namepro = "Bulk-heamap"
   If (namepro == "hmhard" .or. namepro == "hmhardness") set_namepro = "Hardness-heamap"

   If (namepro == 'hmPhaseAll' .or. namepro == 'hmphaseall' .or. namepro == 'hmpall') set_namepro = "Phase-all-heamap"
   If (namepro == 'hmGroupAll' .or. namepro == 'hmgroupall' .or. namepro == 'hmgall') set_namepro = "Group-all-heamap"

   If (namepro == 'hmPFactAll' .or. namepro == 'hmpfoupall' .or. namepro == 'hmpfall') set_namepro = "Power-Flow-all-heamap"
 
   If (namepro == 'hmkm' .or. namepro == 'hmKm' .or. namepro == 'hmKM') set_namepro = "Conductivity-heamap" 
 WRITE(66,"(a)")'<!DOCTYPE html>'
 WRITE(66,"(a)")'<html>'
 WRITE(66,"(a)")'<head>'
 
 WRITE(66,"(a)")"    <title>",trim(set_namepro),"</title>"
 
 WRITE(66,"(a)")'    <script src="./plotly.js"></script>'
 WRITE(66,"(a)")'    <style>'
 WRITE(66,"(a)")'        body {'
 WRITE(66,"(a)")"            font-family: 'Times New Roman', serif;"
 WRITE(66,"(a)")'            display: flex;  '
 WRITE(66,"(a)")'            flex-direction: column;  '
 WRITE(66,"(a)")'            justify-content: flex-start; '
 WRITE(66,"(a)")'            align-items: center;  '
 WRITE(66,"(a)")'            min-height: 100vh;  '
 WRITE(66,"(a)")'            margin: 0;  '
 WRITE(66,"(a)")'            padding-top: 20px;  '
 WRITE(66,"(a)")'        }'
 WRITE(66,"(a)")'        h1 {'
 WRITE(66,"(a)")'            color: #333;  '
 WRITE(66,"(a)")'            font-size: 24px; ' 
 WRITE(66,"(a)")'            margin-bottom: 30px; ' 
  WRITE(66,"(a)")'           text-align: center;  '
 WRITE(66,"(a)")'        }'
 WRITE(66,"(a)")'        .chart-container {'
 WRITE(66,"(a)")'            display: flex;  '
 WRITE(66,"(a)")'            flex-direction: row;  '
 WRITE(66,"(a)")'            justify-content: center;  '
 WRITE(66,"(a)")'            align-items: center;  '
 WRITE(66,"(a)")'            gap: 10px '
 WRITE(66,"(a)")'            '
 WRITE(66,"(a)")'        }'
 WRITE(66,"(a)")'        .chart {'
 WRITE(66,"(a)")'           '
 WRITE(66,"(a)")'        }'
 WRITE(66,"(a)")'    </style>'
 WRITE(66,"(a)")'</head>'
 WRITE(66,"(a)")'<body>'
 WRITE(66,"(a)")' '
 WRITE(66,"(a)")'    <h1> Generated by ElATools ©2024 </h1>'

END SUBROUTINE
