
!```````````````````````````````````````````````````````````````````````````````````````````
! Copyright (c) 2018 Shahram Yalameha <yalameha93@gmail.com> , <sh.yalameha@sci.ui.ac.ir>, `
!               Please report bugs or suggestions to:  yalameha93@gmail.com                `
!                                                                                          `
!```````````````````````````````````````````````````````````````````````````````````````````
SUBROUTINE stitle_web()
  IMPLICIT NONE
  WRITE(66,"(3a)")'    <h2>Generated by ElATools Ⓒ2021-2026 </h2>'
  WRITE(66,"(a)")'<div class="plot3D">'
END SUBROUTINE
!===============================
SUBROUTINE stitle_web2D()
  IMPLICIT NONE
  WRITE(66,"(3a)")'<h1> Generated by ElATools Ⓒ2021-2026 </h1>'
  WRITE(66,"(a)")'<div class="plot">'
END SUBROUTINE
!===============================
SUBROUTINE start_layout_web()
  IMPLICIT NONE
! WRITE(66,"(a)")'<div id="Elatools" style="width: 600px; height: 600px; display:block;" class="js-plotly-plot">'
! WRITE(66,"(a)")'<script type="text/javascript">'
WRITE(66,"(a)")'    <div class="plot-container">'
WRITE(66,"(a)")'        <div id="Elatools" style="width: 100%; height: 750px;"></div>'
WRITE(66,"(a)")'    </div>'
WRITE(66,"(a)")'          '
WRITE(66,"(a)")'    <script type="text/javascript">'
WRITE(66,"(a)")"        var commonLighting = { ambient: 0.8, diffuse: 0.8, specular: 0.05, roughness: 0.9, fresnel: 0.06 };"
WRITE(66,"(a)")"        var commonHoverTemplate = '<b>X:</b> %{x:.4f}<br><b>Y:</b> %{y:.4f}<br><b>Z:</b> %{z:.4f}<extra></extra>';"
  END SUBROUTINE
